### ISSUE TITLE
How to generate json data

### ISSUE THREAD

**Issue by XiankangTang** [materialsgenomefoundation/espei.org#1]
Dear Dr. Bocklund,

I hope this message finds you well. I am currently working on converting .exp files for Thermo-Calc calculations into the JSON format required by ESPEI but have not come across any automated solutions for this task. I was wondering if you might know of any tools or methods that could help streamline this process.

**Comment by bocklund** [comment]
We worked on a POP file parser several years ago. It's very incomplete, but might be useful https://github.com/phasesresearchlab/popparsing

**Comment by XiankangTang** [comment]
I appreciate your help, but I found something when I ran that code.   When I tried to run popparsing 1H.POP [output_file.json], some error happened. 

popparsing 1H.POP output_file.json 
Traceback (most recent call last):
  File "/home/phD/xiankang/anaconda3/envs/espei/bin/popparsing", line 33, in <module>
    sys.exit(load_entry_point('popparsing==0.0.1+33.gd6f15f1', 'console_scripts', 'popparsing')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: main() missing 2 required positional arguments: 'infile' and 'outfile'  

I would be very grateful if you could give me more examples.

**Comment by bocklund** [comment]
I apologize, but I don't have the bandwidth to support popparsing right now. Issues in this repo are dedicated to the espei.org website.
